version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX...
      - sudo yum update -y
      - sudo yum install httpd -y
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls -la
      - sudo cp index.html /var/www/html/       # Copy index.html to the correct location
  post_build:
    commands:
      - echo Configuring and starting NGINX...
artifacts:
  files:
    - '**/*'
